/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.47
 * Generated at: 2020-03-12 03:13:58 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.ex02;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class ex06_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<script type=\"text/javascript\" src=\"https://code.jquery.com/jquery-3.4.1.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t$(function(){\r\n");
      out.write("\t\t$(\"#btn1\").click(function(){\r\n");
      out.write("\t\t\t//$(\".student\").css({color:\"black\",background:\"white\"});\r\n");
      out.write("\t\t\t//$(\".team1\").css({color:\"red\",background:\"skyblue\"});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$(\".team1\").css(\"display\",\"block\");\r\n");
      out.write("\t\t\t$(\".team1\").css(\"display\",\"none\");\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\"#btn2\").click(function(){\r\n");
      out.write("\t\t\t$(\".student\").css({color:\"black\",background:\"white\"});\r\n");
      out.write("\t\t\t$(\".team2\").css({color:\"red\",background:\"skyblue\"});\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\"#man0\").click(function(){\r\n");
      out.write("\t\t\t$(\".student\").css({color:\"black\",background:\"white\"});\r\n");
      out.write("\t\t\t$(\".manager\").css({color:\"red\",background:\"skyblue\"});\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\"#man1\").click(function(){\r\n");
      out.write("\t\t\t$(\".student\").css({color:\"black\",background:\"white\"});\r\n");
      out.write("\t\t\t$(\".team1.manager\").css({color:\"red\",background:\"skyblue\"});\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\"#man2\").click(function(){\r\n");
      out.write("\t\t\t$(\".student\").css({color:\"black\",background:\"white\"});\r\n");
      out.write("\t\t\t$(\".team2.manager\").css({color:\"red\",background:\"skyblue\"});\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<p class=\"student team1\">1.이종호</p>\r\n");
      out.write("\t<p class=\"student team1\">2.전은진</p>\r\n");
      out.write("\t<p class=\"student team2\">3.김혜선</p>\r\n");
      out.write("\t<p class=\"student team2\">4.하지연</p>\r\n");
      out.write("\t<p class=\"student team1\">5.홍수지</p>\r\n");
      out.write("\t<p class=\"student team1 manager\" >6.이동현</p>\r\n");
      out.write("\t<p class=\"student team1\">7.서동욱</p>\r\n");
      out.write("\t\r\n");
      out.write("\t<p class=\"student team1\">8.박유철</p>\r\n");
      out.write("\t<p class=\"student team2\">9.고요한</p>\r\n");
      out.write("\t<p class=\"student team2\">10.유현성</p>\r\n");
      out.write("\t<p class=\"student team1\">11.김정규</p>\r\n");
      out.write("\t<p class=\"student team2\">12.곽설아</p>\r\n");
      out.write("\t<p class=\"student team2\">13.박도형</p>\r\n");
      out.write("\t<p class=\"student team2 manager\">14.이근희</p>\r\n");
      out.write("\t\r\n");
      out.write("\t<button id=\"btn1\">팀1의 구성원</button>\r\n");
      out.write("\t<button id=\"btn2\">팀2의 구성원</button>\r\n");
      out.write("\t<button id=\"man0\">모든관리자</button>\r\n");
      out.write("\t<button id=\"man1\">팀1의 관리자</button>\r\n");
      out.write("\t<button id=\"man2\">팀2의 관리자</button>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
