/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.47
 * Generated at: 2020-02-05 06:04:50 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.ArrayList;
import com.bit.dao.BoardDAO;
import com.bit.vo.BoardVO;
import com.oreilly.servlet.MultipartRequest;

public final class boardOK_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t");

		request.setCharacterEncoding("UTF-8");
		String path = request.getRealPath("img");	//파일의 실제경로 읽어오기
		MultipartRequest multi = new MultipartRequest(request, path, "UTF-8");
		
		int no = 0;
		String title = multi.getParameter("title");
		String writer = multi.getParameter("writer");
		String pwd = multi.getParameter("pwd");
		int hit = 0;
		String regdate = multi.getParameter("regdate");
		String content = multi.getParameter("content");
		String fname = multi.getOriginalFileName("fname");
		
		BoardVO vo = new BoardVO(no, title, writer, pwd, hit, regdate, content, fname);
		BoardDAO dao = new BoardDAO();
		int a = dao.insertBoard(vo);
		
		if(a > 0){
			System.out.println("게시물 등록에 성공하였습니다.");
		}else{
			System.out.println("게시물 등록에 실패하였습니다.");
		}
	
		ArrayList<BoardVO> list = new ArrayList<BoardVO>();
		list = dao.listBoard();
	
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t<h2>게시판 목록</h2>\r\n");
      out.write("\t<hr>\r\n");
      out.write("\t<table width=\"70%\">\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td>번호</td>\r\n");
      out.write("\t\t<td>제목</td>\r\n");
      out.write("\t\t<td>작성자</td>\r\n");
      out.write("\t</tr>\t\r\n");
      out.write("\t");

		for( BoardVO b : list ){
			
      out.write("\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>");
      out.print(b.getNo() );
      out.write("</td>\r\n");
      out.write("\t\t\t\t<td>");
      out.print(b.getTitle() );
      out.write("</td>\r\n");
      out.write("\t\t\t\t<td>");
      out.print(b.getWriter() );
      out.write("</td>\r\n");
      out.write("\t\t\t");

		}
	
      out.write("\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t</table>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
