/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.47
 * Generated at: 2020-02-07 07:28:43 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.goods;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.bit.vo.GoodsVO;
import com.bit.dao.GoodsDAO;

public final class detailGoods_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t");

		int no = Integer.parseInt(request.getParameter("no"));
		GoodsDAO dao = new GoodsDAO();
		GoodsVO g = dao.getGoods(no);
	
      out.write("\r\n");
      out.write("\t<h2>상품 상세설명</h2>\r\n");
      out.write("\t<hr>\r\n");
      out.write("\t파일명 : ");
      out.print(g.getFname() );
      out.write("<br>\r\n");
      out.write("\t<img src =\"../upload/");
      out.print(g.getFname() );
      out.write("\"width=\"150\" height=\"150\"><br>\r\n");
      out.write("\t상품번호 :");
      out.print(g.getNo() );
      out.write("<br> \r\n");
      out.write("\t상품명 : ");
      out.print(g.getItem() );
      out.write("<br>\r\n");
      out.write("\t가격 : ");
      out.print(g.getPrice() );
      out.write("<br>\r\n");
      out.write("\t수량 : ");
      out.print(g.getQty() );
      out.write("<br>\r\n");
      out.write("\t상품설명 : <br>\r\n");
      out.write("\t<textarea rows=\"10\"cols=\"40\"readonly=\"readonly\">");
      out.print(g.getDetail() );
      out.write("</textarea>\r\n");
      out.write("\t<hr>\r\n");
      out.write("\t<a href = \"insertGoods.html\">상품등록</a>\r\n");
      out.write("\t<a href = \"listGoods.jsp\">상품목록</a>\r\n");
      out.write("\t<a href = \"updateGoods.jsp?no=");
      out.print(g.getNo());
      out.write("\">상품수정</a>\r\n");
      out.write("\t<a href = \"deleteGoods.jsp?no=");
      out.print(g.getNo());
      out.write("\">상품삭제</a>\t\r\n");
      out.write("\t\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
