/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.47
 * Generated at: 2020-02-07 12:33:47 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.goods;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.io.File;
import com.bit.dao.GoodsDAO;
import com.bit.vo.GoodsVO;
import com.oreilly.servlet.MultipartRequest;

public final class updateGoodsOK_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t");

		GoodsDAO dao = new GoodsDAO();
		request.setCharacterEncoding("UTF-8");
		//파일의 실제 경로를 알아올 수 있음 getRealPath
		String path = request.getRealPath("upload");
		
		System.out.println(path);
		MultipartRequest multi = new MultipartRequest(request,path,"UTF-8");
		int no = Integer.parseInt(multi.getParameter("no"));
		
		//상품을 수정하기 전에 원래 상품사진 파일명을 담아둡니다.
		String oldFname = dao.getGoods(no).getFname();
	
		String item = multi.getParameter("item");
		int price = Integer.parseInt(multi.getParameter("price"));
		int qty = Integer.parseInt(multi.getParameter("qty"));
		
		//새로 업로드 할 상품사진이름을 담아와요.
		String fname = multi.getOriginalFileName("fname");
		String detail = multi.getParameter("detail");
	
		GoodsVO gv = new GoodsVO();	
		//상품번호는 시퀀스를 통해 자동으로 부여됨으로 설정하지 않아요.	
		gv.setNo(no);
		gv.setItem(item);
		gv.setPrice(price);
		gv.setQty(qty);
		gv.setDetail(detail);
			
		//상품사진을 수정하지 않으면 원래의 사진이름을 vo에 담고 
		//상품사진도 수정한다면 새로 업로드한 사진이름을 vo에 담아요.
		gv.setFname(oldFname);
		if(fname != null){
			gv.setFname(fname);
		}
		
		int re = dao.updateGoods(gv);
		
		if(re > 0){
			if(fname != null){
				File file = new File(path +"/"+ oldFname);
				file.delete();
			}
			response.sendRedirect("listGoods.jsp");
		}else{
			
      out.write("\r\n");
      out.write("\t\t\t상품수정에 실패하였습니다.\r\n");
      out.write("\t\t\t");
	
		}

	
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
