/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.47
 * Generated at: 2020-02-07 02:12:19 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.bit.dao.BoardDAO;
import com.bit.vo.BoardVO;

public final class detailBoard_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t");

		int no = Integer.parseInt(request.getParameter("no"));
		BoardDAO dao = new BoardDAO();
		BoardVO b = dao.getBoard(no);
	
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t글번호 : ");
      out.print(b.getNo() );
      out.write("<br>\r\n");
      out.write("\t작성자 : ");
      out.print(b.getWriter() );
      out.write("<br>\r\n");
      out.write("\t제목 : ");
      out.print(b.getTitle() );
      out.write("<br>\r\n");
      out.write("\t조회수 : ");
      out.print(b.getHit() );
      out.write("<br>\r\n");
      out.write("\t글내용 : <br>\r\n");
      out.write("\t<textarea row=\"10\" cols=\"80\" readonly=\"readonly\">");
      out.print(b.getContent() );
      out.write("</textarea><br>\r\n");
      out.write("\t등록일 : ");
      out.print(b.getRegdate() );
      out.write("<br>\r\n");
      out.write("\tip주소 : ");
      out.print(b.getIp());
      out.write("<br>\r\n");
      out.write("\t파일명 : ");
      out.print(b.getFname() );
      out.write("<br>\r\n");
      out.write("\t");

		if(dao.isImage(b.getFname())){
			
      out.write("\r\n");
      out.write("\t\t\t\t<img src=\"upload/");
      out.print(b.getFname() );
      out.write("\"width=\"200\" height=\"200\">\r\n");
      out.write("\t\t\t");

		}
	
      out.write("\r\n");
      out.write("\t<hr>\r\n");
      out.write("\t<a href=\"insertBoard.jsp\">새글등록</a>\r\n");
      out.write("\t<a href=\"listBoard.jsp\">글 목록</a>\r\n");
      out.write("\t<a href=\"updateBoard.jsp?no=");
      out.print(b.getNo());
      out.write("\">글 수정</a>\r\n");
      out.write("\t<a href=\"deleteBoard.jsp?no=");
      out.print(b.getNo());
      out.write("\">글 삭제</a>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
