/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.47
 * Generated at: 2020-02-07 01:46:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.bit.dao.BoardDAO;
import com.bit.vo.BoardVO;
import com.oreilly.servlet.MultipartRequest;

public final class insertBoardOK_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t");

		//사용자가 요청한 문자는 한글임을 설정합니다.
		request.setCharacterEncoding("UTF-8");
		
		//파일을 복사할 실경로를 얻어옵니다.
		String path = request.getRealPath("upload");
		System.out.println(path);
		
		//파일을 업로드 하면서 사용자의 입력정보를 받아오기 위한 
		//MultipartRequest객체를 생성합니다. 
		MultipartRequest multi = new MultipartRequest(request, path, "UTF-8");
		
		//업로드한 파일은 위에서 MultipartRequest 객체 생성시에 이미 복사가 되었습니다. 
		//이제 나머지 정보들 (글제목,작성자,글내용,암호)을 multi를 통해서 받아옵니다. 
		BoardVO b = new BoardVO();
		b.setTitle(multi.getParameter("title"));
		b.setWriter(multi.getParameter("writer"));
		b.setPwd(multi.getParameter("pwd"));
		b.setContent(multi.getParameter("content"));
	
		//IP주소를 받아온다.
		b.setIp(request.getRemoteAddr());
		
		//파일이름은 이렇게 하면 안돼요! 
		//b.setFname(multi.getParameter("fname")
		//파일명이 오는것이 아니라 파일의 내용이 오기때문에 위와같이 담을 수 없음 
		
		//파일명도 담아오기	multi.getOriginalFileName
		b.setFname(multi.getOriginalFileName("fname"));
		
		BoardDAO dao = new BoardDAO();
		int re = dao.insertBoard(b);
		if(re > 0){

			
      out.write("\r\n");
      out.write("\t\t\t\t게시물 등록에 성공하였습니다.\r\n");
      out.write("\t\t\t");
 
		}else{
			
      out.write("\r\n");
      out.write("\t\t\t\t게시물 등록에 실패하였습니다.\r\n");
      out.write("\t\t\t");
 
		}

	
      out.write("\r\n");
      out.write("\t<hr>\r\n");
      out.write("\t<a href=\"insertBoard.jsp\">새글등록</a>\r\n");
      out.write("\t<a href=\"listBoard.jsp\">글 목록</a>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
