/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.47
 * Generated at: 2020-02-06 08:30:06 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.oreilly.servlet.MultipartRequest;
import java.io.File;
import com.bit.vo.BoardVO;
import com.bit.dao.BoardDAO;

public final class updateBoardOK_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t");

		BoardDAO dao = new BoardDAO();
		request.setCharacterEncoding("UTF-8");
		
		String path = request.getRealPath("upload");
		System.out.println(path);
		
		MultipartRequest multi = new MultipartRequest(request, path, "UTF-8");	
		int no = Integer.parseInt(multi.getParameter("no"));
		
		//원래 게시물에 파일이 있는경우 파일을 지울지 말지의 정보
		//isDel을 받아옵니다.
		String isDel = multi.getParameter("isDel");
		System.out.println("isDel:" + isDel);

		//수정을 하기전에 미리 원래파일명을 저장해둡니다. 
		String oldFname = dao.getBoard(no).getFname();
		String fname = multi.getOriginalFileName("fname");
		BoardVO b = new BoardVO();
		
		
		b.setNo(no);
		b.setTitle(multi.getParameter("title"));
		b.setPwd(multi.getParameter("pwd"));
		b.setContent(multi.getParameter("content"));
		
		//일단 원래 파일의 이름을 vo에 담고
		//만약 파일도 수정한다면 새로운 파일명을 vo에 담아요.
		b.setFname(oldFname);
		if(fname != null){
			b.setFname(fname);
		}
		if( isDel != null ){
			b.setFname(null);
		}
		
		int re = dao.updateBoard(b);
		
		//게시물 수정에 성공했고, 그 게시물이 원래 파일이 있는 게시물 이었고
		//또, 파일도 수정했다면 원래 파일은 삭제해요.
		if(re > 0){
			
			if(oldFname != null && fname != null){
				File file = new File(path + "/" + oldFname);
				file.delete();
			}
			
		//원래는 파일이 있었고 게시물 수정에 성공했고, 파일을 지우기를 원한다면...
			if(isDel != null && isDel.equals("1")){
				File file = new File(path+ "/" + oldFname);
				file.delete();
			}
			
      out.write("\r\n");
      out.write("\t\t\t\t게시물 수정에 성공하였습니다.\r\n");
      out.write("\t\t\t");
 
		
		}else{
			//수정에 실패했을때 파일은 업로드가 되버림. 그걸 지우도록  
			if(fname != null){
				File file = new File(path+ "/" + fname);
				file.delete();
			}
			
			
      out.write("\r\n");
      out.write("\t\t\t\t게시물 수정에 실패하였습니다.\r\n");
      out.write("\t\t\t");
 
		}

	
      out.write("\r\n");
      out.write("\t<hr>\r\n");
      out.write("\t<a href=\"insertBoard.jsp\">새글등록</a>\r\n");
      out.write("\t<a href=\"listBoard.jsp\">글 목록</a>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
