/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.47
 * Generated at: 2020-03-13 09:13:14 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.ex03;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class ex12_002d2_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("#canvas {\r\n");
      out.write("\tborder: solid 1px black;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"https://code.jquery.com/jquery-1.7.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("$(function(){\r\n");
      out.write("\tvar canvas = document.getElementById(\"canvas\");\r\n");
      out.write("\tvar context = canvas.getContext(\"2d\");\r\n");
      out.write("\tvar position= $(canvas).offset();\r\n");
      out.write("\tvar colorArr = [\"red\", \"green\", \"blue\"];\r\n");
      out.write("\t\r\n");
      out.write("\tvar action = 0;\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"span\").css(\"background\",function(idx){\r\n");
      out.write("\t\t//$(this).attr(\"idx\",idx);\r\n");
      out.write("\t\treturn colorArr[idx];\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t$(canvas).mousedown(function(event){\r\n");
      out.write("\t\taction = 1;\r\n");
      out.write("\t\tvar x = event.pageX - position.left;\r\n");
      out.write("\t\tvar y = event.pageY - position.top;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tcontext.beginPath();\r\n");
      out.write("\t\tcontext.moveTo(x,y);\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t$(canvas).mousemove(function(event){\r\n");
      out.write("\t\tif(action == 1){\r\n");
      out.write("\t\tvar x = event.pageX - position.left;\r\n");
      out.write("\t\tvar y = event.pageY - position.top;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tcontext.lineTo(x,y);\r\n");
      out.write("\t\tcontext.stroke();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t$(canvas).mouseup(function(){\r\n");
      out.write("\t\taction = 0;\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"span\").click(function(){\r\n");
      out.write("\t\tvar color = $(this).css(\"background-color\");\r\n");
      out.write("\t\t//var color =  colorArr[ $(this).attr(\"idx\") ];\t\r\n");
      out.write("\t\tcontext.strokeStyle = color;\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"#btn\").click(function(){\r\n");
      out.write("\t\t$(\"#img\").attr (\"src\", canvas.toDataURL(\"image/jpg\") );\r\n");
      out.write("\t});\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<canvas id=\"canvas\" width=\"400\" height=\"400\"></canvas>\r\n");
      out.write("\t<hr>\r\n");
      out.write("\t<span>빨간색</span>\r\n");
      out.write("\t<span>초록색</span>\r\n");
      out.write("\t<span>파랑색</span>\r\n");
      out.write("\t<hr>\r\n");
      out.write("\t<button id=\"btn\">그림가져오기</button>\r\n");
      out.write("\t<img id=\"img\">\t<!-- 내가 그린그림이 img에 표시되게 -->\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
