/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.47
 * Generated at: 2020-02-04 07:41:25 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.GregorianCalendar;
import java.util.Calendar;

public final class calendar2_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");

	GregorianCalendar cal = new GregorianCalendar();
	int year = cal.get(Calendar.YEAR);
	int mon = cal.get(Calendar.MONTH);
	int date = cal.get(Calendar.DATE);
	int[] lastday = {31,28,31,30,31,30,31,31,30,31,30,31};
	int last = lastday[mon];
	if(cal.isLeapYear(year)){
		last = 29;
	}
	
	GregorianCalendar startday = new GregorianCalendar(year, mon, 1);
	int start = startday.get(Calendar.DAY_OF_WEEK);
	mon++;
	

      out.write("\r\n");
      out.write("<h2>");
      out.print(year );
      out.write('년');
      out.write(' ');
      out.print(mon );
      out.write("월</h2>\r\n");
      out.write("\r\n");
      out.write("<table border=\"1\" width=\"50%\" height=\"400\">\r\n");
      out.write("<tr bgcolor=\"pink\">\r\n");
      out.write("\t<td>일</td>\r\n");
      out.write("\t<td>월</td>\r\n");
      out.write("\t<td>화</td>\r\n");
      out.write("\t<td>수</td>\r\n");
      out.write("\t<td>목</td>\r\n");
      out.write("\t<td>금</td>\r\n");
      out.write("\t<td>토</td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");

for(int i=1; i<start; i++){
	
      out.write("\r\n");
      out.write("\t\t<td></td>\r\n");
      out.write("\t");

}
for(int i=1; i<=last; i++){
	if(i==date){
		
      out.write("\r\n");
      out.write("\t\t<td bgcolor=\"yellow\">");
      out.print(i );
      out.write("</td>\r\n");
      out.write("\t\t");

	}else{
		if((i+start-1)%7==0){
		
      out.write("\r\n");
      out.write("\t\t\t<td><font color=\"blue\">");
      out.print(i );
      out.write("</font></td>\r\n");
      out.write("\t\t");

		}else if((i+start-1)%7==1){
		
      out.write("\r\n");
      out.write("\t\t\t<td><font color=\"red\">");
      out.print(i );
      out.write("</font></td>\r\n");
      out.write("\t\t");
	
		}else {
			
      out.write("\r\n");
      out.write("\t\t\t<td>");
      out.print(i );
      out.write("</td>\r\n");
      out.write("\t\t");
	
		}
	}
	if((i+start-1)%7==0){
	
      out.write("\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t");

	}
}	

      out.write("\r\n");
      out.write("</tr>\r\n");
      out.write("</table>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
