/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.47
 * Generated at: 2020-03-10 11:50:36 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp._0310;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class ex04_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\twindow.onload = function() {\r\n");
      out.write("\t\tvar li;\r\n");
      out.write("\t\tvar s;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tdocument.getElementById(\"btn\").onclick = function() {\r\n");
      out.write("\r\n");
      out.write("\t\t\tli = document.createElement(\"li\");\r\n");
      out.write("\t\t\tvar show = document.getElementById(\"in\");\r\n");
      out.write("\r\n");
      out.write("\t\t\tli.onclick = function() {\r\n");
      out.write("\t\t\t\ts = this\r\n");
      out.write("\t\t\t\tshow.value = this.innerHTML;\t//input창에 선택한 li의 내용이 보이도록\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tvar liList = document.getElementsByTagName(\"li\");\r\n");
      out.write("\t\t\t\tfor(var i = 0; i <liList.length;i++){\r\n");
      out.write("\t\t\t\t\tliList[i].style.background = \"white\";\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\ts.style.background =\"coral\";\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tdocument.getElementById(\"del\").onclick = function(){\r\n");
      out.write("\t\t\t\t\ts.parentNode.removeChild(s);\t\r\n");
      out.write("\t\t\t\t\t//s는 onclick에서 선택한 this 이다. 그 this의 부모를 찾고 지워줘!\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\tvar txt = document.getElementById(\"in\").value;\r\n");
      out.write("\t\t\t//여기까진 동일 \r\n");
      out.write("\r\n");
      out.write("\t\t\t// 이 아래 두줄은 appendChild 쓸때\r\n");
      out.write("\t\t\t//var a = document.createTextNode(txt);\r\n");
      out.write("\t\t\t//li.appendChild(a);\r\n");
      out.write("\r\n");
      out.write("\t\t\tli.innerHTML = txt;\r\n");
      out.write("\r\n");
      out.write("\t\t\tdocument.getElementById(\"ul\").appendChild(li);\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<ul id=\"ul\"></ul>\r\n");
      out.write("\t<input type=\"text\" id=\"in\">\r\n");
      out.write("\t<button id=\"btn\">등록</button>\r\n");
      out.write("\t<button id=\"del\">삭제</button>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
