/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.47
 * Generated at: 2020-03-13 01:11:31 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.ex01;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class ex01_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<script type=\"text/javascript\" src=\"https://code.jquery.com/jquery-3.4.1.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t$(function(){\r\n");
      out.write("\t\tvar arr = [\r\n");
      out.write("\t\t\t{no:1, name:\"스타킹1\", price:1000, qty:10, fname:\"stock1.jpg\"},\r\n");
      out.write("\t\t\t{no:2, name:\"스타킹2\", price:2000, qty:10, fname:\"stock2.jpg\"},\r\n");
      out.write("\t\t\t{no:3, name:\"스타킹3\", price:3000, qty:10, fname:\"stock3.jpg\"},\r\n");
      out.write("\t\t\t{no:4, name:\"스타킹4\", price:4000, qty:10, fname:\"stock4.jpg\"},\r\n");
      out.write("\t\t\t{no:5, name:\"스타킹5\", price:5000, qty:10, fname:\"stock5.jpg\"}\r\n");
      out.write("\t\t\t];\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$.each(arr, function(idx, item){\r\n");
      out.write("\t\t\tvar li = $(\"<li></li>\").html(\"<h2>\" +item.no + \"/\" +item.name + \"</h2>\");\r\n");
      out.write("\t\t\t$(li).attr(\"idx\",idx);\r\n");
      out.write("\t\t\t$(\"#list\").append(li);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$(\"li\").click(function(){\r\n");
      out.write("\t\t\t\tvar idx = $(this).attr(\"idx\");\r\n");
      out.write("\t\t\t\tvar g = arr[idx];\r\n");
      out.write("\t\t\t\t$(\"#img\").attr(\"src\", g.fname);\r\n");
      out.write("\t\t\t\t$(\"#no\").html(g.no);\r\n");
      out.write("\t\t\t\t$(\"#name\").html(g.name);\r\n");
      out.write("\t\t\t\t$(\"#qty\").html(g.qty);\r\n");
      out.write("\t\t\t\t$(\"#price\").html(g.price);\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<ul id=\"list\"></ul>\r\n");
      out.write("\t<table>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td><img id=\"img\" width=\"100\" height=\"100\"></td>\r\n");
      out.write("\t\t\t<td>\r\n");
      out.write("\t\t\t\t<p id=\"no\"></p>\r\n");
      out.write("\t\t\t\t<p id=\"name\"></p>\r\n");
      out.write("\t\t\t\t<p id=\"qty\"></p>\r\n");
      out.write("\t\t\t\t<p id=\"price\"></p>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t</table>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
