/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.47
 * Generated at: 2020-03-13 04:02:32 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.ex01;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class ex17_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"https://code.jquery.com/jquery-3.4.1.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t$(function() {\r\n");
      out.write("\t\t//팀원명을 더블클릭하면 해당 팀원을 삭제합니다. \r\n");
      out.write("\t\t//각 버튼의 처리도 하기\r\n");
      out.write("\t\t//선택한 항목에 하이라이트를 설정하고, 선택한 항목의 내용을 텍스트필드에 출력합니다.\r\n");
      out.write("\t\t//수정에 대한 기능을 구현합니다.\r\n");
      out.write("\t\tvar info;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\"h2\").click(function(){\r\n");
      out.write("\t\t\t$(\"h2\").css(\"background\",\"white\");\r\n");
      out.write("\t\t\t$(this).css(\"background\",\"skyblue\");\r\n");
      out.write("\t\t\tvar txt = $(this).text();\r\n");
      out.write("\t\t\t$(\"#addMember\").val(txt);\r\n");
      out.write("\t\t\tinfo = $(this);\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\"#btnUpdate\").click(function(){\r\n");
      out.write("\t\t\tvar up =$(\"#addMember\").val();\r\n");
      out.write("\t\t\t$(info).html(up);\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\"h2\").dblclick(function() {\r\n");
      out.write("\t\t\t$(this).remove();\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t$(\"#addT1\").click(function() {\r\n");
      out.write("\t\t\t//var member = $(\"#addMember\").val();\r\n");
      out.write("\t\t\t//var h2 = $(\"<h2></h2>\").html(member);\r\n");
      out.write("\t\t\t//$(\"#team1\").append(h2);\r\n");
      out.write("\t\t\t//위는 내가 한 방법, 아래는 한줄로 쓰기\r\n");
      out.write("\t\t\tvar h2 = $(\"<h2></h2>\").html($(\"#addMember\").val());\r\n");
      out.write("\t\t\t$(\"#team1\").append(h2);\r\n");
      out.write("\t\t\t$(h2).dblclick(function() {\r\n");
      out.write("\t\t\t$(this).remove();\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t$(\"#addT2\").click(function() {\r\n");
      out.write("\t\t\tvar member = $(\"#addMember\").val();\r\n");
      out.write("\t\t\tvar h2 = $(\"<h2></h2>\").html(member);\r\n");
      out.write("\t\t\t$(\"#team2\").append(h2);\r\n");
      out.write("\r\n");
      out.write("\t\t\t$(h2).dblclick(function() {\r\n");
      out.write("\t\t\t\t$(this).remove();\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t$(\"#delT1\").click(function() {\r\n");
      out.write("\t\t\t$(\"#team1 >h2\").remove();\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t$(\"#delT2\").click(function() {\r\n");
      out.write("\t\t\t$(\"#team2 >h2\").remove();\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<h1>팀1의 구성원</h1>\r\n");
      out.write("\t<div id=\"team1\">\r\n");
      out.write("\t\t<h2>이순신</h2>\r\n");
      out.write("\t\t<h2>유관순</h2>\r\n");
      out.write("\t\t<h2>홍길동</h2>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<hr>\r\n");
      out.write("\t<h1>팀2의 구성원</h1>\r\n");
      out.write("\t<div id=\"team2\">\r\n");
      out.write("\t\t<h2>강감찬</h2>\r\n");
      out.write("\t\t<h2>김유신</h2>\r\n");
      out.write("\t\t<h2>세종대왕</h2>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<input type=\"text\" id=\"addMember\">\r\n");
      out.write("\t<button id=\"addT1\">팀1 추가</button>\r\n");
      out.write("\t<button id=\"addT2\">팀2 추가</button>\r\n");
      out.write("\t<button id=\"btnUpdate\">수정</button>\r\n");
      out.write("\t<br>\r\n");
      out.write("\t<button id=\"delT1\">팀1 모두 삭제</button>\r\n");
      out.write("\t<br>\r\n");
      out.write("\t<button id=\"delT2\">팀2 모두 삭제</button>\r\n");
      out.write("\t<br>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
