/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.47
 * Generated at: 2020-02-17 06:14:03 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.exam02;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class ex01_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\tdiv{\r\n");
      out.write("\t\twidth: 600px;\r\n");
      out.write("\t\theight: 200px;\r\n");
      out.write("\t\tborder: 5px solid;\r\n");
      out.write("\t\tmargin: 20px;\t\t\r\n");
      out.write("\t\tpadding: 30px;\t\t\r\n");
      out.write("\t}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div>\r\n");
      out.write("\t엘튼 존은 지난 16일 뉴질랜드 오클랜드의 마운트 스마트 스타디움에서 월드투어 공연을 하던 중 \r\n");
      out.write("\t“방금 전 목소리를 잃었다”며 “더 이상 노래를 부를 수 없을 것 같다. 이제 가봐야겠다. 미안하다”라고 밝히며 공연을 중단했다. 원인은 워킹 폐렴으로 ‘코로나 19’는 아닌 것으로 전해졌다.\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<div>\r\n");
      out.write("\t올해로 4년째, 겨울도 아니고 절기상으로 입춘이 지난 뒤 중계동 백사마을에서 연탄 나눔 봉사가 있었다.\r\n");
      out.write("\t2월 중순에 이 행사를 하는 이유가 있다. 입춘이 지났지만, 꽃샘추위가 남아있을 뿐 아니라 연탄에 의지해 난방을 하는 이들에게는 월동 준비한 연탄이 떨어져 가는 시기이기 때문이다.\r\n");
      out.write("\t새벽이 오기 전 가장 어둡듯이, 봄바람이 불어오긴 했으되 아직 끝나지 않는 계절이 서민들에게는 가장 추운 계절이기도 하다. 그리하여 김응교 시인을 중심으로 하여 윤동주를 사랑하는 이들이 4년 전부터 이맘때면 '별을 노래하는 마음'으로 연탄 나눔 행사를 펼치고 있는 것이다.\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
