/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.47
 * Generated at: 2020-03-10 05:42:29 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.ex02;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class ex03_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\twindow.onload = function(){\r\n");
      out.write("\t\tvar li;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar newsList = [\r\n");
      out.write("\t\t\t{title:\"코로나19 유럽·중동 확산에 WHO 첫 ‘팬데믹’ 선언\", url:\"https://news.naver.com/main/read.nhn?mode=LSD&mid=shm&sid1=104&oid=022&aid=0003445692\", content:\"신종 코로나바이러스 감염증(코로나19)의 팬데믹(세계적 대유행·pandemic) 정의에 선을 그어온 WHO(세계보건기구)가 9일(현지시간) 처음으로 '팬데믹 위협이 매우 현실화하고 있다'고 내다봤다. 발병지인 중국을 비롯해 인근 국가로 확산하던 코로나19가 유럽, 중동, 미국까지 빠르게 확산하고 있는데 따른 것이다.\"},\r\n");
      out.write("\t\t\t{title:\"트럼프, 코로나 확진자 접촉한 의원과 악수…워싱턴 발칵\", url:\"https://news.naver.com/main/read.nhn?mode=LSD&mid=shm&sid1=104&oid=025&aid=0002982621\", content:\"신종 코로나바이러스 감염증(코로나19) 확진자와 접촉한 하원의원과 접촉한 도널드 트럼프 미국 대통령은 코로나19 진단 검사를 받아야 할까. \"},\r\n");
      out.write("\t\t\t{title:\"[날씨] 전국 흐리고 봄비...비 온 뒤 '찬 바람'\", url:\"https://news.naver.com/main/read.nhn?mode=LSD&mid=shm&sid1=103&oid=052&aid=0001412425\", content:\"오늘 나오실 때는 우산을 꼭 챙기시는 게 좋겠습니다.전국 곳곳에 봄비가 내리고 있는데요.\"},\r\n");
      out.write("\t\t\t{title:\"고국 돌아간다 버려졌지만… 성격 최고 믹스견\", url:\"https://news.naver.com/main/read.nhn?mode=LSD&mid=shm&sid1=103&oid=469&aid=0000474980\", content:\"매주 토요일 서울 이태원 근처 노란천막 아래에서는 자원봉사단체 ‘유기동물행복찾는사람들’(이하 유행사)회원들이 준비한 유기견, 유기묘의 가족 찾기 행사가 열립니다. \"},\r\n");
      out.write("\t\t\t{title:\"하루 100kcal만, 고기 대신 '이것' 먹으면 사망 위험 ↓\", url:\"https://news.naver.com/main/read.nhn?mode=LSD&mid=shm&sid1=103&oid=346&aid=0000030905\", content:\"하루 먹는 식단의 100kcal를 고기 등 동물성 단백질 대신 콩, 견과류, 통곡물 등 식물성 단백질로 바꾸면 사망 위험이 감소한다는 연구 결과가 나왔다.\"}\r\n");
      out.write("\t\t];\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfor(var i = 0; i<newsList.length; i++){\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar news = newsList[i];\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\tli = document.createElement(\"li\");\r\n");
      out.write("\t\t\tvar txt = document.createTextNode(news.title);\r\n");
      out.write("\t\t\tli.appendChild(txt);\r\n");
      out.write("\t\t\tli.setAttribute(\"idx\",i)\r\n");
      out.write("\t\t\tdocument.getElementsByTagName(\"ul\")[0].appendChild(li);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tli.onmouseover = function(){\r\n");
      out.write("\t\t\t\tvar idx = this.getAttribute(\"idx\");\r\n");
      out.write("\t\t\t\tdocument.getElementById(\"content\").value = newsList[idx].content\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<h2>오늘의 주요뉴스</h2>\t\r\n");
      out.write("\t<ul></ul>\r\n");
      out.write("\t<textarea rows=\"10\" cols=\"80\" id=\"content\" ></textarea>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
