/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.47
 * Generated at: 2020-03-10 06:59:11 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.ex02;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class ex07_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\twindow.onload = function(){\r\n");
      out.write("\t\tvar sun = document.getElementById(\"sun\");\r\n");
      out.write("\t\tvar earth = document.getElementById(\"earth\");\r\n");
      out.write("\t\tvar moon = document.getElementById(\"moon\");\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tsun.style.position = \"absolute\";\t//중심\r\n");
      out.write("\t\tearth.style.position = \"absolute\";\r\n");
      out.write("\t\tmoon.style.position = \"absolute\";\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tsun.style.left = 250+'px';\r\n");
      out.write("\t\tsun.style.top = 200+'px';\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar earthAngle = 0;\r\n");
      out.write("\t\tvar moonAngle = 0;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tsetInterval(function(){\r\n");
      out.write("\t\t\t//각도를 사용해 지구와 달의 좌표를 구합니다.\r\n");
      out.write("\t\t\tvar earthLeft = 250 + 150 * Math.cos(earthAngle);\r\n");
      out.write("\t\t\tvar earthTop = 200 + 150 * Math.sin(earthAngle);\r\n");
      out.write("\t\t\tvar moonLeft = earthLeft + 50 * Math.cos(moonAngle);\r\n");
      out.write("\t\t\tvar moonTop = earthTop + 50 * Math.sin(moonAngle);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t//위치를 이동합니다.\r\n");
      out.write("\t\t\tearth.style.left = earthLeft +'px';\r\n");
      out.write("\t\t\tearth.style.top = earthTop +'px';\r\n");
      out.write("\t\t\tmoon.style.left = moonLeft +'px';\r\n");
      out.write("\t\t\tmoon.style.top = moonTop +'px';\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t//각도를 변경합니다.\r\n");
      out.write("\t\t\tearthAngle += 0.1;\r\n");
      out.write("\t\t\tmoonAngle += 0.3;\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t}, 1000/30);\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div id=\"sun\"><img src=\"sun.png\" width=\"50\" height=\"50\"></div>\r\n");
      out.write("\t<div id=\"earth\"><img src=\"earth.png\" width=\"50\" height=\"50\"></div>\r\n");
      out.write("\t<div id=\"moon\"><img src=\"moon.png\" width=\"50\" height=\"50\"></div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
