/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.47
 * Generated at: 2020-03-10 07:49:39 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.ex02;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class ex08_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t/*\r\n");
      out.write("\t\t졸라맨을 좌측하단에 출력합니다.\r\n");
      out.write("\t\t시간이 흐름에 따라 반복하여 오른쪽으로 이동하도록 합니다.\r\n");
      out.write("\t*/\r\n");
      out.write("\t\r\n");
      out.write("\twindow.onload = function(){\r\n");
      out.write("\t\tvar arr =[\"man.png\",\"man2.png\",\"man3.png\",\"sun.png\"];\r\n");
      out.write("\t\tvar man = document.getElementById(\"man\");\r\n");
      out.write("\t\tvar i = 0;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tman.style.position = \"absolute\";\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tman.style.left = 0 +'px';\r\n");
      out.write("\t\tman.style.top = 450+'px';\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar manleft = 0;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tsetInterval(function(){\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tman.style.left = manleft + 50 +'px';\r\n");
      out.write("\t\t\tmanleft += 10;\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tman.childNodes[0].src = arr[i];\r\n");
      out.write("\t\t\ti++;\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif(i >= arr.length){\r\n");
      out.write("\t\t\t\ti = 0;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t}, 100);\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div id=\"man\"><img src=\"man.png\" width=\"80\" height=\"80\"></div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
