/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.47
 * Generated at: 2020-03-10 10:10:04 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class ex01_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("//스크립트는 늘 head안에, 특수한 경우에는 body에도 사용이 가능하다. 디폴트는 헤드!\r\n");
      out.write("\t\r\n");
      out.write("\t//바디를 먼저읽고나서 스크립트를 실행하게된다. \r\n");
      out.write("\twindow.onload = function(){\r\n");
      out.write("\t\t//alert(\"ㅂ\");\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t//var a = document.getElementById(\"btn\");\t\r\n");
      out.write("\t\t//노드를 통째로 가지고온다. 스크립트에서는 변수타입이 var가 주로 쓰인다.\r\n");
      out.write("\t\t//var는 모든 타입에 다 호환이 된다. (자바의 기본형태들을 전부 받아들일 수 있다.)\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t//var b = document.getElementsById(\"h1\");\r\n");
      out.write("\t\t//아이디가 없는걸 가져올땐 tagname 반환은 무조건 배열 '\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t var a  = document.createElement(\"h1\");\r\n");
      out.write("\t\t//노드를 만들어줌. 바디에 없는 노드도 지정할 수 있다. \r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar txt = document.createTextNode(\"타이핑을 해도되고, 변수를 넣어도 된다.\");\r\n");
      out.write("\t\t\r\n");
      out.write("\t\ta.appendChild(txt);\r\n");
      out.write("\t\t// appendChild사용시 부모, 자식이 둘다 노드여야한다. \r\n");
      out.write("\t\t\r\n");
      out.write("\t\tdocument.getElementById(\"dd\").appendChild(a);\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<!-- 노드란, 바디안에서 사용되는 객체(노드) \r\n");
      out.write("\t\t노드와 텍스트노드 구분중요 -->\r\n");
      out.write("\t\t<button id=\"btn\">버튼이다</button>\r\n");
      out.write("\t\t<div id=\"dd\"></div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
