/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.47
 * Generated at: 2020-03-12 09:16:11 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.ex05;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class ex01_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\t.high_light{background: yellow;}\r\n");
      out.write("\t.active{background: pink;}\r\n");
      out.write("</style>\r\n");
      out.write("<script type=\"text/javascript\" src=\"https://code.jquery.com/jquery-3.4.1.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t$(function(){\r\n");
      out.write("\t\tvar inputList = $(\"input[type = text]\");\r\n");
      out.write("\t\tvar tdList;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t//등록\r\n");
      out.write("\t\t$(\"#btnAdd\").click(function(){\r\n");
      out.write("\t\t\tvar tr = $(\"<tr></tr>\").addClass(\"member\");\r\n");
      out.write("\t\t\t$.each(inputList, function(idx, item){\r\n");
      out.write("\t\t\t\tconsole.log(idx);\r\n");
      out.write("\t\t\t\t$(tr).append(\t$(\"<td></td>\").html($(item).val())  );\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t$(\"#tb\").append(tr);\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t//수정\r\n");
      out.write("\t\t$(\"#btnUpdate\").click(function(){\r\n");
      out.write("\t\t\t$.each(inputList, function(idx, item){\r\n");
      out.write("\t\t\t\t$(tdList[idx]).html( $(this).val());\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\".member\").hover(function(){\r\n");
      out.write("\t\t\t$(this).addClass(\"high_light\");\r\n");
      out.write("\t\t}, function(){\r\n");
      out.write("\t\t\t$(this).removeClass(\"high_light\");\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\".member\").click(function(){\r\n");
      out.write("\t\t\t$(\".member\").removeClass(\"active\");\r\n");
      out.write("\t\t\t$(this).addClass(\"active\");\r\n");
      out.write("\t\t\ttdList = $(this).find(\"td\");\r\n");
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$.each(tdList, function(idx, td){\r\n");
      out.write("\t\t\t\t$(inputList[idx]).val(  $(td).html()  );\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<table width=\"80%\" id=\"tb\">\r\n");
      out.write("\t\t<tr><td>이름</td><td>국어</td><td>영어</td><td>수학</td></tr>\r\n");
      out.write("\t\t<tr class=\"member\"><td>홍길동</td><td>55</td><td>77</td><td>99</td></tr>\r\n");
      out.write("\t\t<tr class=\"member\"><td>이순신</td><td>45</td><td>87</td><td>87</td></tr>\r\n");
      out.write("\t\t<tr class=\"member\"><td>유관순</td><td>98</td><td>99</td><td>65</td></tr>\r\n");
      out.write("\t\t<tr class=\"member\"><td>김유신</td><td>54</td><td>34</td><td>65</td></tr>\r\n");
      out.write("\t\t<tr class=\"member\"><td>강감찬</td><td>75</td><td>68</td><td>90</td></tr>\r\n");
      out.write("\t</table>\r\n");
      out.write("\t<br>\r\n");
      out.write("\t<hr>\r\n");
      out.write("\t이름 : <input type=\"text\"><br>\r\n");
      out.write("\t국어 : <input type=\"text\"><br>\r\n");
      out.write("\t영어 : <input type=\"text\"><br>\r\n");
      out.write("\t수학 : <input type=\"text\"><br><br>\r\n");
      out.write("\t<input id=\"btnAdd\" type=\"button\" value=\"등록\">\r\n");
      out.write("\t<input id=\"btnUpdate\" type=\"button\" value=\"수정\">\r\n");
      out.write("\t<input id=\"btnDel\" type=\"button\" value=\"삭제\">\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
